package theperfectfit.sizedoesmatter;

import android.app.Activity;
import android.graphics.Bitmap;
import android.provider.MediaStore;
import android.view.View;
import android.view.Window;

public class SaveMeasurements {

    private SaveMeasurements(){}

    public static void saveTouchImage(Window window, Activity activity){

        Bitmap screenshot = getScreenshot(window);
        DimensionReturn dims = getCoords(activity);

        Bitmap croppedBitmap = Bitmap.createBitmap(screenshot,dims.x,dims.y,dims.width,dims.height);

        MediaStore.Images.Media.insertImage(activity.getContentResolver(),croppedBitmap,"rulr save","Image generated by rulr to save measurments");
    }

    private static Bitmap getScreenshot(Window window){
        View v1 = window.getDecorView().getRootView();
        v1.setDrawingCacheEnabled(true);
        Bitmap bitmap = Bitmap.createBitmap(v1.getDrawingCache());
        v1.setDrawingCacheEnabled(false);

        return bitmap;
    }

    private static DimensionReturn getCoords(Activity activity){

        TouchImageView imgView = (TouchImageView) activity.findViewById(R.id.MainImageView);

        int[] location = new int[2];
        imgView.getLocationOnScreen(location);

        int x = location[0];
        int y = location[1];
        int width = imgView.getFixedWidth();
        int height = imgView.getFixedHeight();

        return new DimensionReturn(x,y,width,height);
    }

}

class DimensionReturn {
    public int x;
    public int y;
    public int width;
    public int height;

    public DimensionReturn(int x, int y, int width, int height) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
}
